# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 13:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20160411_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gundem',
            name='ekleyen_kullanici',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
